server:
  port: 8030
spring:
  data:
    mongodb:
      username: neko
      password: neko
      host: localhost
      port: 27018
      database: notifications
      authentication-database: admin
      #uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/notifications

      spring.json.type.mapping: messageNotification:com.kaiwa.notificationservice.event.message.exchange.MessageNotification

  nats:
    bootstrap-servers: nats://localhost:4222