version: '3.9'
services:
  kaiwa-postgres:
    image: postgres:14.11-alpine3.18
    container_name: ms_kaiwa_postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: neko
      POSTGRES_PASSWORD: neko
      PGDATA: /data/postgres
    volumes:
      - kaiwa-pg-slaves:/data/postgres
    networks:
      - kaiwa-networks

  kaiwa-mongo:
    image: mongo
    container_name: ms_kaiwa_mongo
    ports:
      - 27018:27017
    volumes:
      - kaiwa-mongo-slaves:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neko
      - MONGO_INITDB_ROOT_PASSWORD=neko

  nats:
    image: nats:latest
    container_name: ms_nats_server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8223:8222"
    environment:
      - "JS_ENABLE=true"
    volumes:
      - nats-data:/data
    command: >
      -js
      --store_dir=/data
    networks:
      - kaiwa-networks

networks:
  kaiwa-networks:
    driver: bridge

volumes:
  nats-data:
  kaiwa-pg-slaves:
  kaiwa-mongo-slaves:
